# Generated by Django 4.2.1 on 2023-05-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Müəllimlər'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('male', 'Kişi'), ('female', 'Qadın')], max_length=10, null=True, verbose_name='Cinsi'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Ata adı'),
        ),
    ]
