# Generated by Django 4.2.1 on 2023-05-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_options_teacher_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Ata adı'),
        ),
    ]
