# Generated by Django 4.2.1 on 2023-05-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentgroup_students_alter_studentgroup_starosta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='starosta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student', verbose_name='Starosta'),
        ),
    ]
