# Generated by Django 4.2.1 on 2023-05-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_studentgroup_starosta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kafedra', models.CharField(max_length=250, verbose_name='Kafedra')),
                ('date_start', models.DateField(verbose_name='Başlama tarixi')),
                ('date_end', models.DateField(verbose_name='Başlama tarixi')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentgroup', verbose_name='Qrup')),
            ],
            options={
                'verbose_name_plural': 'Qruplar',
            },
        ),
    ]
