# Generated by Django 4.2.1 on 2023-05-17 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_patronymic'),
        ('students', '0003_alter_studentgroup_starosta'),
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Ad')),
                ('code', models.CharField(max_length=250, verbose_name='Code')),
            ],
            options={
                'verbose_name_plural': 'Fənlər',
            },
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name_plural': 'Jurnallar'},
        ),
        migrations.CreateModel(
            name='JournalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('lecture', 'M'), ('lab', 'L'), ('seminar', 'S'), ('kollokvium', 'K')], max_length=10, verbose_name='Tip')),
                ('hour', models.SmallIntegerField(verbose_name='Saat')),
                ('is_present', models.BooleanField(verbose_name='Davamiyyət')),
                ('mark', models.IntegerField(blank=True, null=True, verbose_name='Qiymət')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journal', verbose_name='Jurnal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Tələbə')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentgroup', verbose_name='Qrup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.subject', verbose_name='Fən')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Müəllim')),
            ],
            options={
                'verbose_name_plural': 'Jurnallar Yazıları',
            },
        ),
    ]
